### ISSUE TITLE
Document the code size status and goals

### ISSUE THREAD

**Issue by juj** [pjoe/wasm-naga#1]
The question of network transfer cost came up at https://github.com/gpuweb/gpuweb/issues/845#issuecomment-640238731 - I wonder what would be the expected kBytes cost to embed a SPIR-V -> WGSL or a GLSL->SPIR-V transformation path? (or too early stages to tell?)

**Comment by juj** [comment]
Noticed that current build in the repo is 568523 bytes of wasm, or 186137 bytes gzipped. I wonder if "final" version will likely be smaller, larger, or about the same size?

**Comment by pjoe** [comment]
Yeah, the aim is basically as small as possible :D Compared to size of current JS engines (BJS, Three) being in couple of 100KB (gz), I would like to aim <100KB, but let's see what is possible with current state of rust and wasm. FWIW: I did initial tests with naga WGSL > MSL which was ~200KB (no gz).

Currently investigating better options for the parser in the GLSL frontend, that will produce a smaller binary.
